### ISSUE TITLE
Dose Estimation produce "subscript out of bounds" in 3.2.0 (dev-branch)

### ISSUE THREAD

**Issue by Gaetan-IRSN** [biodosetools-team/biodosetools#9]
### Bug report/feedback

- Assessment: Dicentrics/Dose Estimation
- Module: Acute/Whole Body dose estimation

After loading data using .rds, and input data (C0:480, C1:20), selecting Acute and Whole body, the dose estimation produces "subscript out of bounds" error:
![image](https://user-images.githubusercontent.com/60822731/74319951-13b4f380-4d80-11ea-8e27-bcace8026517.png)

R console 

> Warning: Error in [<-: subscript out of bounds
>   185: reactive:data [modules/generalEstimateModules.R#769]
>   183: .func
>   180: contextFunc
>   179: env$runWith
>   172: ctx$run
>   171: self$.updateValue
>   169: data
>   168: renderPlot [modules/generalEstimateModules.R#1191]
>   166: func
>   126: drawPlot
>   112: reactive:plotObj
>    96: drawReactive
>    83: origRenderFunc
>    82: output$dicent_estimate-plot
>     2: shiny::runApp
>     1: runApp
> Warning: Error in [<-: subscript out of bounds
>   102: Anonymous
> Warning: Error in [<-: subscript out of bounds
>   102: Anonymous

and

> Warning: Error in [<-: subscript out of bounds
>   116: reactive:data [modules/generalEstimateModules.R#769]
>   100: data
>    96: func [modules/generalEstimateModules.R#1020]
>    83: origRenderFunc
>    82: output$dicent_estimate-est_yields_whole
>     2: shiny::runApp
>     1: runApp
> Warning: Error in [<-: subscript out of bounds
>   102: Anonymous
> Warning: Error in [<-: subscript out of bounds
>   171: Anonymous

**Comment by Gaetan-IRSN** [comment]
On the online version (https://aldomann.shinyapps.io/biodose-tools-beta/_w_b7e02338/_w_ab289c0a/), the issue seems to be reproduced depending on the .rds file used.

Issue occurs using this rds, generated by the offline version 3.2.0:
[dicentrics-fitting-data-2020-02-12.zip](https://github.com/biodosimetry-uab/biodosetools/files/4192095/dicentrics-fitting-data-2020-02-12.zip)
![image](https://user-images.githubusercontent.com/60822731/74335833-56d18f80-4d9d-11ea-9b41-9e1b4ce44fc4.png)

The issue could not be reproduced on the online version using this rds generated by the online version: 
[dicentrics-fitting-data-2020-02-05.zip](https://github.com/biodosimetry-uab/biodosetools/files/4192124/dicentrics-fitting-data-2020-02-05.zip)
![image](https://user-images.githubusercontent.com/60822731/74336319-4d94f280-4d9e-11ea-8c1c-1c7da3cb9634.png)


However, the 2 rds files produce ""subscript out of bounds" error using the offline version 3.2.0

The 2 rds files analysed directly in R seems to be identical... 

```
eric<-readRDS("O:/dicentrics-fitting-data-2020-02-05.rds")
gae<-readRDS("O:/dicentrics-fitting-data-2020-02-12.rds")
```
`gae[["fit_raw_data"]]==eric[["fit_raw_data"]]`
>          D    N    X   C0   C1   C2   C3   C4   C5   C6 mean  var   DI    u
>  [1,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [2,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [3,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [4,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [5,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [6,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [7,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [8,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [9,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [10,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [11,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [12,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [13,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [14,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [15,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [16,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [17,] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

`round(gae$fit_coeffs, digits = 4)==round(eric$fit_coeffs, digits = 4)`

>   estimate std.error statistic p.value
> C     TRUE      TRUE      TRUE    TRUE
> a     TRUE      TRUE      TRUE    TRUE
> ß     TRUE      TRUE      TRUE    TRUE

`round(gae$fit_var_cov_mat, digits = 10)==round(eric$fit_var_cov_mat, digits = 10)`

>      C    a    ß
> C TRUE TRUE TRUE
> a TRUE TRUE TRUE
> ß TRUE TRUE TRUE

**Comment by Gaetan-IRSN** [comment]
The bug can not be reproduce when .rds file is generated with 3.2.0. 
It may come from alpha and beta characters used for $fit_formula_raw, only difference between the rds file that produces the "subscript out of bounds" error and the one that does not induce the error.

Suggest to close the issue that may be link to the issue #5

**Comment by aldomann** [comment]
This issue was introduced by the change of internal variable names for C, alpha, and beta in v3.2.0. Note that v3.3.0 can't read `dicentrics-fitting-data-2020-02-12.rds` either.

By creating a new fitting RDS object with the same count data (see table below), v3.3.0 is able to estimate the case C0: 480, C1: 20 with no issues.

Fixing #5 will likely cause some breakage in legacy RDS files as well, as it will require a substantial rewrite for some functions. This should however the last breaking change fix.

| D    | C0    | C1  | C2 | C3 | C4 | C5 |
|------|-------|-----|----|----|----|----|
| 0.0  | 19173 | 21  |    |    |    |    |
| 0.05 | 1674  | 3   |    |    |    |    |
| 0.1  | 1546  | 6   |    |    |    |    |
| 0.15 | 478   | 3   |    |    |    |    |
| 0.24 | 1046  | 11  |    |    |    |    |
| 0.3  | 1730  | 38  |    |    |    |    |
| 0.33 | 1169  | 18  |    |    |    |    |
| 0.5  | 2837  | 81  | 1  |    |    |    |
| 0.8  | 1444  | 89  | 4  | 1  |    |    |
| 1    | 783   | 82  | 4  |    |    |    |
| 1.6  | 1278  | 225 | 22 |    |    |    |
| 2    | 1365  | 421 | 51 | 6  | 1  |    |
| 2.3  | 248   | 91  | 9  | 3  | 1  |    |
| 3    | 425   | 264 | 76 | 13 | 5  |    |
| 4    | 199   | 199 | 94 | 34 | 8  |    |
| 4.7  | 98    | 146 | 67 | 20 | 9  | 1  |
| 5.77 | 23    | 27  | 23 | 17 | 2  | 1  |
